// Copyright 2019 Radiation Detection and Imaging (RDI), LLC
// Use of this source code is governed by the BSD 3-clause
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/rdi/sim/simple.proto

package sim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Particle struct {
	Parent               []uint64 `protobuf:"varint,1,rep,packed,name=parent,proto3" json:"parent,omitempty"`
	Child                []uint64 `protobuf:"varint,2,rep,packed,name=child,proto3" json:"child,omitempty"`
	Pdg                  int32    `protobuf:"zigzag32,3,opt,name=pdg,proto3" json:"pdg,omitempty"`
	Vertex               *XYZTF   `protobuf:"bytes,4,opt,name=vertex,proto3" json:"vertex,omitempty"`
	P                    *XYZF    `protobuf:"bytes,5,opt,name=p,proto3" json:"p,omitempty"`
	Mass                 float32  `protobuf:"fixed32,6,opt,name=mass,proto3" json:"mass,omitempty"`
	Charge               int32    `protobuf:"zigzag32,7,opt,name=charge,proto3" json:"charge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Particle) Reset()         { *m = Particle{} }
func (m *Particle) String() string { return proto.CompactTextString(m) }
func (*Particle) ProtoMessage()    {}
func (*Particle) Descriptor() ([]byte, []int) {
	return fileDescriptor_d083313703f9f43a, []int{0}
}

func (m *Particle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Particle.Unmarshal(m, b)
}
func (m *Particle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Particle.Marshal(b, m, deterministic)
}
func (m *Particle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Particle.Merge(m, src)
}
func (m *Particle) XXX_Size() int {
	return xxx_messageInfo_Particle.Size(m)
}
func (m *Particle) XXX_DiscardUnknown() {
	xxx_messageInfo_Particle.DiscardUnknown(m)
}

var xxx_messageInfo_Particle proto.InternalMessageInfo

func (m *Particle) GetParent() []uint64 {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Particle) GetChild() []uint64 {
	if m != nil {
		return m.Child
	}
	return nil
}

func (m *Particle) GetPdg() int32 {
	if m != nil {
		return m.Pdg
	}
	return 0
}

func (m *Particle) GetVertex() *XYZTF {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *Particle) GetP() *XYZF {
	if m != nil {
		return m.P
	}
	return nil
}

func (m *Particle) GetMass() float32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *Particle) GetCharge() int32 {
	if m != nil {
		return m.Charge
	}
	return 0
}

type SimHit struct {
	VolumeId      uint64  `protobuf:"varint,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	GlobalPrePos  *XYZTF  `protobuf:"bytes,2,opt,name=global_pre_pos,json=globalPrePos,proto3" json:"global_pre_pos,omitempty"`
	GlobalPostPos *XYZTF  `protobuf:"bytes,3,opt,name=global_post_pos,json=globalPostPos,proto3" json:"global_post_pos,omitempty"`
	EDep          float32 `protobuf:"fixed32,4,opt,name=e_dep,json=eDep,proto3" json:"e_dep,omitempty"`
	Particle      uint64  `protobuf:"varint,5,opt,name=particle,proto3" json:"particle,omitempty"`
	// Alternate fields
	VolumeName           string   `protobuf:"bytes,6,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	ParticleName         string   `protobuf:"bytes,7,opt,name=particle_name,json=particleName,proto3" json:"particle_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimHit) Reset()         { *m = SimHit{} }
func (m *SimHit) String() string { return proto.CompactTextString(m) }
func (*SimHit) ProtoMessage()    {}
func (*SimHit) Descriptor() ([]byte, []int) {
	return fileDescriptor_d083313703f9f43a, []int{1}
}

func (m *SimHit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimHit.Unmarshal(m, b)
}
func (m *SimHit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimHit.Marshal(b, m, deterministic)
}
func (m *SimHit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimHit.Merge(m, src)
}
func (m *SimHit) XXX_Size() int {
	return xxx_messageInfo_SimHit.Size(m)
}
func (m *SimHit) XXX_DiscardUnknown() {
	xxx_messageInfo_SimHit.DiscardUnknown(m)
}

var xxx_messageInfo_SimHit proto.InternalMessageInfo

func (m *SimHit) GetVolumeId() uint64 {
	if m != nil {
		return m.VolumeId
	}
	return 0
}

func (m *SimHit) GetGlobalPrePos() *XYZTF {
	if m != nil {
		return m.GlobalPrePos
	}
	return nil
}

func (m *SimHit) GetGlobalPostPos() *XYZTF {
	if m != nil {
		return m.GlobalPostPos
	}
	return nil
}

func (m *SimHit) GetEDep() float32 {
	if m != nil {
		return m.EDep
	}
	return 0
}

func (m *SimHit) GetParticle() uint64 {
	if m != nil {
		return m.Particle
	}
	return 0
}

func (m *SimHit) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *SimHit) GetParticleName() string {
	if m != nil {
		return m.ParticleName
	}
	return ""
}

type XYZF struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZF) Reset()         { *m = XYZF{} }
func (m *XYZF) String() string { return proto.CompactTextString(m) }
func (*XYZF) ProtoMessage()    {}
func (*XYZF) Descriptor() ([]byte, []int) {
	return fileDescriptor_d083313703f9f43a, []int{2}
}

func (m *XYZF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XYZF.Unmarshal(m, b)
}
func (m *XYZF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XYZF.Marshal(b, m, deterministic)
}
func (m *XYZF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZF.Merge(m, src)
}
func (m *XYZF) XXX_Size() int {
	return xxx_messageInfo_XYZF.Size(m)
}
func (m *XYZF) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZF.DiscardUnknown(m)
}

var xxx_messageInfo_XYZF proto.InternalMessageInfo

func (m *XYZF) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZF) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZF) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type XYZTF struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	T                    float32  `protobuf:"fixed32,4,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XYZTF) Reset()         { *m = XYZTF{} }
func (m *XYZTF) String() string { return proto.CompactTextString(m) }
func (*XYZTF) ProtoMessage()    {}
func (*XYZTF) Descriptor() ([]byte, []int) {
	return fileDescriptor_d083313703f9f43a, []int{3}
}

func (m *XYZTF) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XYZTF.Unmarshal(m, b)
}
func (m *XYZTF) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XYZTF.Marshal(b, m, deterministic)
}
func (m *XYZTF) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XYZTF.Merge(m, src)
}
func (m *XYZTF) XXX_Size() int {
	return xxx_messageInfo_XYZTF.Size(m)
}
func (m *XYZTF) XXX_DiscardUnknown() {
	xxx_messageInfo_XYZTF.DiscardUnknown(m)
}

var xxx_messageInfo_XYZTF proto.InternalMessageInfo

func (m *XYZTF) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *XYZTF) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *XYZTF) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *XYZTF) GetT() float32 {
	if m != nil {
		return m.T
	}
	return 0
}

func init() {
	proto.RegisterType((*Particle)(nil), "rdi.sim.Particle")
	proto.RegisterType((*SimHit)(nil), "rdi.sim.SimHit")
	proto.RegisterType((*XYZF)(nil), "rdi.sim.XYZF")
	proto.RegisterType((*XYZTF)(nil), "rdi.sim.XYZTF")
}

func init() { proto.RegisterFile("proto/rdi/sim/simple.proto", fileDescriptor_d083313703f9f43a) }

var fileDescriptor_d083313703f9f43a = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xab, 0x13, 0x31,
	0x14, 0x25, 0x99, 0x8f, 0xf6, 0xdd, 0xd7, 0x3e, 0x35, 0x8a, 0x84, 0xd7, 0x85, 0xc3, 0x08, 0x32,
	0xab, 0xa9, 0xa8, 0xb8, 0x15, 0x44, 0x8a, 0x6e, 0xa4, 0x44, 0x17, 0xda, 0xcd, 0x30, 0xed, 0x84,
	0x36, 0x30, 0x69, 0x42, 0x12, 0x4b, 0xdb, 0x9f, 0xe0, 0x5f, 0xf2, 0xcf, 0x49, 0x32, 0xa9, 0xb8,
	0xe8, 0xe2, 0x2d, 0x06, 0xee, 0x39, 0x73, 0x0e, 0xf7, 0x9e, 0x43, 0xe0, 0x5e, 0x1b, 0xe5, 0xd4,
	0xdc, 0x74, 0x62, 0x6e, 0x85, 0xf4, 0x9f, 0xee, 0x79, 0x1d, 0x48, 0x32, 0x32, 0x9d, 0xa8, 0xad,
	0x90, 0xe5, 0x1f, 0x04, 0xe3, 0x65, 0x6b, 0x9c, 0xd8, 0xf4, 0x9c, 0x3c, 0x87, 0x5c, 0xb7, 0x86,
	0xef, 0x1d, 0x45, 0x45, 0x52, 0xa5, 0x2c, 0x22, 0xf2, 0x0c, 0xb2, 0xcd, 0x4e, 0xf4, 0x1d, 0xc5,
	0x81, 0x1e, 0x00, 0x79, 0x0c, 0x89, 0xee, 0xb6, 0x34, 0x29, 0x50, 0xf5, 0x84, 0xf9, 0x91, 0xbc,
	0x82, 0xfc, 0xc0, 0x8d, 0xe3, 0x47, 0x9a, 0x16, 0xa8, 0xba, 0x7d, 0x73, 0x57, 0xc7, 0x35, 0xf5,
	0x8f, 0x9f, 0xab, 0xef, 0x0b, 0x16, 0xff, 0x92, 0x19, 0x20, 0x4d, 0xb3, 0x20, 0x99, 0xfe, 0x2f,
	0x59, 0x30, 0xa4, 0x09, 0x81, 0x54, 0xb6, 0xd6, 0xd2, 0xbc, 0x40, 0x15, 0x66, 0x61, 0xf6, 0x87,
	0x6d, 0x76, 0xad, 0xd9, 0x72, 0x3a, 0x0a, 0xdb, 0x22, 0x2a, 0x7f, 0x63, 0xc8, 0xbf, 0x09, 0xf9,
	0x59, 0x38, 0x32, 0x83, 0x9b, 0x83, 0xea, 0x7f, 0x49, 0xde, 0x88, 0x8e, 0xa2, 0x02, 0x55, 0x29,
	0x1b, 0x0f, 0xc4, 0x97, 0x8e, 0xbc, 0x83, 0xbb, 0x6d, 0xaf, 0xd6, 0x6d, 0xdf, 0x68, 0xc3, 0x1b,
	0xad, 0x2c, 0xc5, 0x57, 0x0f, 0x9c, 0x0c, 0xaa, 0xa5, 0xe1, 0x4b, 0x65, 0xc9, 0x7b, 0x78, 0x74,
	0x71, 0x29, 0xeb, 0x82, 0x2d, 0xb9, 0x6a, 0x9b, 0x46, 0x9b, 0xb2, 0xce, 0xfb, 0x9e, 0x42, 0xc6,
	0x9b, 0x8e, 0xeb, 0xd0, 0x02, 0x66, 0x29, 0xff, 0xc4, 0x35, 0xb9, 0x87, 0xb1, 0x8e, 0x3d, 0x87,
	0xe8, 0x29, 0xfb, 0x87, 0xc9, 0x0b, 0xb8, 0x8d, 0xb7, 0xef, 0x5b, 0xc9, 0x43, 0xf2, 0x1b, 0x06,
	0x03, 0xf5, 0xb5, 0x95, 0x9c, 0xbc, 0x84, 0xe9, 0x45, 0x3c, 0x48, 0x46, 0x41, 0x32, 0xb9, 0x90,
	0x5e, 0x54, 0xbe, 0x86, 0xd4, 0x77, 0x48, 0x26, 0x80, 0x8e, 0xa1, 0x01, 0xcc, 0xd0, 0xd1, 0xa3,
	0x53, 0x48, 0x8b, 0x19, 0x3a, 0x79, 0x74, 0x0e, 0x21, 0x30, 0x43, 0xe7, 0xf2, 0x03, 0x64, 0x21,
	0xc0, 0xc3, 0x2d, 0x1e, 0xb9, 0x98, 0x0b, 0xb9, 0x8f, 0xd9, 0x2a, 0xb1, 0x42, 0xae, 0xf3, 0xf0,
	0xa8, 0xde, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xc8, 0xe1, 0xde, 0x72, 0x02, 0x00, 0x00,
}
